// ..AUTH
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

// UNAUTH
export const UNAUTH_USER = 'UNAUTH_USER'

// ..signup
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

// ...
export const RESEND_VERIFYCODE_SUCCESS = 'RESEND_VERIFYCODE_SUCCESS'
export const RESEND_VERIFYCODE_FAIL = 'RESEND_VERIFYCODE_FAIL'

// ...
export const CLEAR_SERVER_ERRORS = 'CLEAR_SERVER_ERRORS'